script: "bundle exec rspec ./spec/"
sudo: false
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/1.8
    - rvm: ree
      gemfile: gemfiles/1.8
    - rvm: 1.9.2
      gemfile: gemfiles/1.9.2
