script: "bundle exec rspec ./spec/"
sudo: false
language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
gemfile:
  - gemfiles/nokogiri_1.6.gemfile
  - gemfiles/nokogiri_latest.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/nokogiri_latest.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/nokogiri_latest.gemfile
